version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '19011:6379'
  app:
    image: testokur-light:latest
    build: .
    ports:
      - '8066:8066'
    depends_on:
      - redis
  